package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setPersonId(java.lang.Integer personId) {
		set("person_id", personId);
	}
	
	public java.lang.Integer getPersonId() {
		return getInt("person_id");
	}

	public void setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
	}
	
	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public void setCheck(java.lang.Integer check) {
		set("check", check);
	}
	
	public java.lang.Integer getCheck() {
		return getInt("check");
	}

	public void setInside(java.lang.String inside) {
		set("inside", inside);
	}
	
	public java.lang.String getInside() {
		return getStr("inside");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setRetire(java.lang.String retire) {
		set("retire", retire);
	}
	
	public java.lang.String getRetire() {
		return getStr("retire");
	}

}
