package com.wts.entity.model;

import com.wts.entity.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File().dao();
}
