package com.wts.entity.model;

import com.wts.entity.base.BaseFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flow extends BaseFlow<Flow> {
	public static final Flow dao = new Flow().dao();
}
