package com.wts.entity.model;

import com.wts.entity.base.BaseFunc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Func extends BaseFunc<Func> {
	public static final Func dao = new Func().dao();
}
