package com.wts.entity.model;

import com.wts.entity.base.BasePower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Power extends BasePower<Power> {
	public static final Power dao = new Power().dao();
}
